name: Env Example

on:
  push:
    branches: [ main ]

env:
  APP_ENV: development

jobs:
  example:
    runs-on: ubuntu-latest
    # steps:
    #   - run: echo "App environment is $APP_ENV"
    steps:
    - name: Print stage variable
    run: echo "Stage = $STAGE"
    env:
      STAGE: test
