name: Multi Jobs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building project"

  test:
    # runs-on: ubuntu-latest
    # steps:
    #   - run: echo "Running tests"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Running tests after build"


  